### ISSUE TITLE
Tiles disappear after Pizza Face spawns.. (and the color glitch is still happening.)

### ISSUE THREAD

**Issue by DuskDragonNight75** [GithubSPerez/pt-new-level-editor#29]
So I was playing a bit more and I found this bug too, where tiles disappear after pizza face spawns and it makes things basically unplayable... also I've still been having the color glitch with my tiles.

https://github.com/GithubSPerez/pt-new-level-editor/assets/100539847/be039eda-6235-4f53-a554-361b9164c258

**Comment by 06NinjaKid06** [comment]
these don't happen to me is that just because I don't use custom tiles?

**Comment by DuskDragonNight75** [comment]
@06NinjaKid06 probably

**Comment by GithubSPerez** [comment]
this shouldn't happen with custom tilesets either.
after looking at the clip frame by frame I'm noticing the colors fade slowly, same thing with pizzaface spawning. that is the transition that happens when you touch a secret tile layer. please make sure you're only using that layer with tiles you intend to disappear when touched.

**Comment by miroslav2027** [comment]
Same thing happend to me, I am on main layer not on secret and after a while it dissapears. Also, it feels like it happens when I walk past some point.
